### ISSUE TITLE
Support video playback

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#121]
As done in this PR: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/607

**Comment by bummytime** [comment]
Related: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/626

**Comment by aforcier** [comment]
Video playback support to-do list:
- [x] Opening posts with existing videos on self-hosted<sup>1</sup>
- [x] Opening posts with existing videos on WP.com<sup>2</sup>

<sup>1</sup> Adding video from wp-admin on self-hosted sites adds `[video]` tags. Currently, the iOS editor doesn't support these, and they show up as shortcodes (no video playback). We'll have the same limitation out of the box since this relies on changes to the `ZSSEditor`. (ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/3911)
<sup>2</sup> On WP.com sites we rely on VideoPress, and `[wpvideo]` shortcodes need to be converted to `<video>` tags for playback (and back to shortcodes for uploading).

**Comment by aforcier** [comment]
I'm splitting off video insertion into a separate issue (#274) to keep the video PRs at a reasonable size.

**Comment by aforcier** [comment]
Added in https://github.com/wordpress-mobile/WordPress-Android/pull/3626.
