### ISSUE TITLE
Keyboard disappears after tapping in editor

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Editor-Android#165]
I can't repro this consistency, but sometimes when I tap in the editor after typing a title the keyboard disappears. [Video demo](https://cloudup.com/cUz88RZP-FE).

Note that tapping again in the editor doesn't cause the keyboard to re-appear, so there doesn't seem to be a way to type the post when this happens.

(Nexus 6,  Android 5.1)

**Comment by aforcier** [comment]
@tonyr59h reported what sounds like the same issue. The problem appears to be that the editor doesn't respond to taps below the last line of text (this is not intended behaviour).

So if the content field is empty, the keyboard will only pop up if you tap at the very top of the field (where the first line will be once you start typing). Otherwise it appears that the editor has stopped responding.

**Comment by aforcier** [comment]
The bug is due to the content field not automatically expanding to fill the HTML body:

https://cloudup.com/cw8OQOfyTVd

As content is typed in, the content field expands until finally it takes up all the white space and the issue is gone.
