### ISSUE TITLE
Can't start a post with formatted text

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#204]
Pressing **B** or **I** in a new post and then typing will turn the style button back off and won't apply it.

Doesn't look to be an `API 19+` autocorrect issue, could reproduce on an `API18` Samsung S3.

Demo video: https://cloudup.com/cPrhIt_F0DW

Original ref: https://github.com/wordpress-mobile/WordPress-Android/pull/3018#issuecomment-125737183

**Comment by aforcier** [comment]
iOS counterpart issue: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/754

**Comment by rachelmcr** [comment]
Discovered again in alpha testing by Mo, Moto X 2, Android 6.0.

**Comment by aforcier** [comment]
Demo GIF:

![wp-android-visual-editor-1](https://cloud.githubusercontent.com/assets/7233112/13757414/aa86a0da-e9fa-11e5-873c-fd4278d4c809.gif)

**Comment by ghost** [comment]
This bug and another bug related to Korean, Vietnamese language break to the newline happened because of the very first line of editor (inside zss_field_content) wasn't wrap in any html tag. I fixed it by check if field is empty them wrap it in <p> tag.

//=>1.This editor can't start with Vietnamese, Korean, Japaneese character...(not latin one), it make very first line break to new line
//=>2.This editor can't start with text format: Bold, Italic, Strikethought, Align right

ZSSEditor.wrapEmptyParent = function() {
    var contenEditable = document.getElementById('zss_field_content');

```
if(contenEditable.innerHTML == 0) {
    contenEditable.innerHTML = '<p>\u200b</p>';

    var range = document.createRange();
    var sel = window.getSelection();
    range.setStart(contenEditable.childNodes[0],0);
    range.setEnd(contenEditable.childNodes[0],1);
    range.collapse(false);
    range.deleteContents();
    sel.removeAllRanges();
    sel.addRange(range);
    contenEditable.focus();

}
```

};
