### ISSUE TITLE
Rich text post preview (pre-publish mode, lists)

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-Android#223]
Currently, blog post preview shows lists in HTML when editing a post in WYSIWYG mode (pre-publish preview)- should be rich text

![](https://cloudup.com/iOf2Ja-XFQn+)

samsung sm-t

**Comment by aforcier** [comment]
From discussion elsewhere, it looks like we'll be dropping the in-editor preview for release, with a view to re-add it in the future when it can fully support live previewing (with a correctly formatted and themed post preview rather than a local preview).

This issue will instead involve disabling the editor preview for the new editor (but keeping it in for the legacy editor).

**Comment by aforcier** [comment]
Merged in https://github.com/wordpress-mobile/WordPress-Android/pull/3774.
