### ISSUE TITLE
Add support for inserting galleries

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#239]
Make sure gallery insertion and adding multiple images with the new media picker are fully supported.
- [x] Adding galleries
- [x] Adding multiple images

**Comment by aforcier** [comment]
Uploading multiple images seems to be working in WPAndroid (they're uploaded sequentially).

**Comment by bummytime** [comment]
@meremagee Do you have any opinions regarding galleries in the 1st cut of the new editor? (e.g. do we absolutely need this functionality out of the gate?)

**Comment by aforcier** [comment]
I put together a basic demo for gallery support with the new editor.

First, here's the flow on the legacy editor:

https://cloudup.com/co7o23hWxMY

A placeholder image is added, and the shortcode is added when the post is uploaded/updated. The placeholder image is used whether the gallery uses local device images or already uploaded WP media library images.

My proposal for a first pass on galleries for the new editor is to simply display the shortcode:

![239-gallery-demo](https://cloud.githubusercontent.com/assets/9613966/11151758/cf2b2e46-89fc-11e5-8fc3-e78e22ef73b0.png)

In the future we could display the gallery visually instead.

Here's a demo using images from the blog's media library:

https://cloudup.com/cdeARiL76jH

For local images, the existing media picker uploads the images right away along with a notification (you can see it in the status bar in the demo). So I'm using a placeholder shortcode and then replacing it with the real shortcode when the images finish uploading:

https://cloudup.com/c65PiSqfkkn

What do you all think of this approach? @bummytime @thianhlu @meremagee

**Comment by thianhlu** [comment]
:+1: Better than the current flow and consistent between media lib vs local files.

**Comment by meremagee** [comment]
I generally don't think exposing editable shortcodes to users makes for a great UX. Best case, users are fluent in optional shortcode parameters and somehow know the image id for assets in their media library. Worst case, shortcodes look like a failure message or unfinished process, and users accidentally insert unwanted text or corrupt the editable shortcode. 

Here are various states in the legacy editor, none of which make sense or transition with any context: https://cloudup.com/c8Ti3nip0B0. I think inserting shortcode immediately in editor is an improvement over the current flow because it's consistent. But, I'm conflicted because I also believe shortcodes are poor UX. I would almost rather persist a placeholder/icon if possible post-publish (but I'm guessing it's not since those are real post artifacts and not placeholders once the post hits the server?).

Let's go with this for the short term and clean it up (insert visual gallery) asap. Great work, @aforcier

**Comment by aforcier** [comment]
> I generally think exposing editable shortcodes to users doesn't make for a great UX.

Agreed. It would be great to replace this with a way to represent the gallery visually, and swap out for the shortcode when uploading/updating/switching to HTML mode (not simple but definitely possible). 

Using a placeholder instead would be easier (though probably not by very much) and still an improvement over the bare shortcode, though in either case we're not really helping the user know _which_ gallery they're looking at - a placeholder isn't much worse than image ids (especially since you could still see the ids by switching to HTML mode).

I'll open a separate issue for visual gallery and go ahead with the shortcode version.

**Comment by aforcier** [comment]
Implemented and merged in https://github.com/wordpress-mobile/WordPress-Android/pull/3465.
