### ISSUE TITLE
Open a Post for edition, don't modify it, but get "Local changes"

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Editor-Android#295]
1. Tap "Edit" on a published post,
2. Don't edit the post, 
3. Tap back - get the "Local changes saved" Toast.

**Comment by maxme** [comment]
Full steps:
1. Start a new post with "Test" as title and "Test" as content,
2. Publish it,
3. Wait for it to be published,
4. Tap "Edit" on that published post,
5. Don't edit the post, 
6. Tap back - get the "Local changes saved" Toast.

**Comment by aforcier** [comment]
This specific case turns out to be WPAndroid side, with a mistake when comparing categories (`&amp;` becoming `&`) (https://github.com/wordpress-mobile/WordPress-Android/issues/3788).

However there's a different case that can happen with multi-line posts (not it all cases, however) and actually is an editor issue. The editor sometimes replaces line breaks `\n` with `\n\n`, and that difference sets off the diff checker on the WPAndroid side.

**Comment by aforcier** [comment]
The `\n>\n\n` bug only seems to happen for posts with video tags, and won't happen if you switch to HTML mode and back an odd number of times.

**Comment by aforcier** [comment]
Related: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/70

**Comment by aforcier** [comment]
> The `\n>\n\n` bug only seems to happen for posts with video tags, and won't happen if you switch to HTML mode and back an odd number of times.

This was fixed with https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/418, video paragraph formatting conversion is now consistent and I can't get a false 'local changes' dialog to appear anymore with video posts.

**Comment by aforcier** [comment]
With #70 closed, it looks like all known cases of this issue have been addressed.

Closing this issue for now, we'll reopen it if we discover a new case.
