### ISSUE TITLE
Can't exit blockquote

### ISSUE THREAD

**Issue by thomasguillot** [wordpress-mobile/WordPress-Editor-Android#299]
I want to add a new paragraph after a blockquote but I don't seem to be able to? The only solution is to switch to the HTML editor.

![2016-02-25 13 57 38](https://cloud.githubusercontent.com/assets/177929/13321622/0610ca98-dbc8-11e5-9904-0f6b8ce0749c.png)

**Comment by aforcier** [comment]
@thomasguillot are you able to exit the blockquote by starting a new paragraph and then re-pressing the blockquote button (so that it becomes unhighlighted)?

This behavior doesn't match the web editor (where double-enter escapes from the blockquote), but I believe the consideration (from the original iOS editor implementation) was that making it work that way on mobile would prevent the user from writing multiple paragraphs _inside_ a blockquote.

We've had another report of being stuck inside a blockquote though, so changing it to behave like the web editor is worth considering.

cc @meremagee

**Comment by thomasguillot** [comment]
@aforcier Oh! Yes I am able to exit the blockquote. I was trying to move the cursor outside of the blockquote. I think without any documentation it's not very clear that I need to create a new paragraph then click on the blockquote button again.
