### ISSUE TITLE
Pasting text and editing it results in extra lines

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#315]
This looks to be the same as or very similar to https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/783 in the iOS visual editor. cc @hoverduck who mentioned the issue in the Android visual editor, which led to my testing:

**Steps to reproduce:**
1. Copy a block of text and paste into the editor
2. Select a word in the text
3. Backspace (to try to delete the word) or type something (to try to overwrite the word)

Result: Lines breaks are added to the text. If you backspace the selected word, the first letter of that word isn't erased and the new line starts with the following word. If you type something, your typing starts on the new line. Trying to backspace again will result in more new lines added.

I reproduced this each time I copied and pasted text into the editor, no matter the source (including when I copied text that I had previously typed directly into the editor and then pasted it into the editor again).

Tested on Nexus 9, Android 6.0.1, app version alpha-2.

**Comment by kwonye** [comment]
Repro'd on Nexus 6P, Android 6.0.1, version alpha-4 as well

**Comment by aforcier** [comment]
From my testing this seems to only happen when the editor is empty (the pasted text is not wrapped in paragraph tags, causing the editing bugs).

However, I am seeing that formatting will be kept if you cut and paste text within the editor, which will sometimes nest the pasted text inside existing paragraph tags (instead of pasting them at the top layer).
