### ISSUE TITLE
Deleting a remote post discards all posts' local changes

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#33]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/2183

If there are one or more posts with local changes and any remote (non-local draft) post is deleted, the local changes of all posts are discarded without warning.

**Comment by maxme** [comment]
The problem is a bit different now and local changes are not lost:
- Edit a published post with wpandroid, don't publish the changes.
- Go back to the Post list, you should see a "Local changes" notice on the post you just edited
- Move this post to trash on the Web
- Refresh the post list in wpandroid: the post and local changes are still there
- Publish the local changes and notice the post move from trash to published (IMO, that's the correct behavior)

A problem appears when you delete the post completely:
- Edit a published post with wpandroid, don't publish the changes.
- Go back to the Post list, you should see a "Local changes" notice on the post you just edited
- **Delete the post completely**
- Refresh the post list in wpandroid: the post and local changes are still there
- Publish the local changes and get an error: "Invalid post ID [404]" which seems normal. Error message comes from the XMLRPC response, not ideal.

I think it's an acceptable behavior if we had a better message.

**Comment by aforcier** [comment]
Migrating back to WPAndroid since it's a post list issue.
