### ISSUE TITLE
Exiting the editor while uploading media causes a failed upload and glitchy behavior

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#346]
If you exit the editor while uploading media, it causes a failed upload without any warning. In addition, opening the post again in the editor causes glitchy behavior:
- If you tap to retry the upload, no progress bar appears
- After the upload finishes, the `span` tag for the failed upload and the `progress` tag for the progress bar are still in the post HTML
- If you don't retry the upload, and try to switch to the HTML view instead, you get the "remove failed uploads" prompt — and that prompt reappears every time you try to switch between HTML and visual even after removing the failed uploads

That same glitchy behavior also occurs if you exit the editor without removing any failed uploads from the post.

We should prevent the user from exiting the editor if media is uploading or if there are still failed uploads in the post. Here are examples for what happens in the iOS app in those cases: https://cloudup.com/cFUIbC6QfCE
### Steps to reproduce

Retrying a failed upload:
1. Open the app and start a new post
2. Start uploading a new image to the post
3. Tap the back button to leave the editor during the upload
4. Open the draft in the editor again
5. Tap to retry the media upload. No progress bar appears during upload.
6. After the upload finishes, switch to HTML view. HTML for the failed upload and progress bar are still there.

Removing a failed upload:
1. Open the app and start a new post
2. Start uploading a new image to the post
3. Tap the back button to leave the editor during the upload
4. Open the draft in the editor again
5. Try to switch to HTML view.
6. On the prompt that appears, select "remove failed uploads." The failed uploads are removed.
7. Try to switch back to visual view. The prompt appears again even though all failed uploads were already removed.

**Comment by aforcier** [comment]
This is caused by an oversight in the regex converting `p`s to `div`s and back. [Here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/6d51447bb97ad3433fe8b94a9fec7284f3ac3741/libs/editor-common/assets/ZSSRichTextEditor.js#L3412) and [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/6d51447bb97ad3433fe8b94a9fec7284f3ac3741/libs/editor-common/assets/ZSSRichTextEditor.js#L3444), we should match the entire opening `p` and `div` tag. The `<p` partial match was mistakenly replacing part of the `progress` tag, breaking the upload container when re-opening a post with a failed upload.

**Comment by aforcier** [comment]
A better idea would be to match `<p` or `<p` and `<div` or `<div` (with spaces), in case we add classes or ids to paragraph separators in the future.
