### ISSUE TITLE
Replace Dashicons with gridicons in the format bar 

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#370]
We should replace the dashicons with [gridicons](http://automattic.github.io/gridicons/).

It may also be time to replace the `HTML` button with code tags, as the iOS editor already has: 

![gridicons-code](https://cloud.githubusercontent.com/assets/9613966/15016982/ba4f72ee-11e1-11e6-8b08-68fb9be7a67d.png)

cc @jasmussen

**Comment by aforcier** [comment]
This is also relevant to the iOS editor, cc @diegoreymendez

**Comment by aforcier** [comment]
Re: HTML mode button

On the other hand, keeping it as `HTML` is more consistent with the Calypso editor:

<img width="712" alt="screen shot 2016-05-05 at 9 05 01 am" src="https://cloud.githubusercontent.com/assets/9613966/15044117/a42d83ec-12a0-11e6-9f71-2b3f180461bc.png">

My vote is to leave it for now, I think @maxme is also in agreement.

**Comment by maxme** [comment]
> My vote is to leave it for now, I think @maxme is also in agreement.

Yes, it's more explicit than the icon and doesn't take too much space.

**Comment by jasmussen** [comment]
Here's a zip file containing all the icons you should need. 

3 colors, base, disabled and highlighted. SVG, vector drawables, and PNGs.

Note, the SVGs, share the same base grid size as Gridicons do, at 24dp. I'm assuming since they're vectors, you can easily upsize them to the 44dp size that the format icons appear to be using. On that note, have you considered using them in 48dp size instead? That would make the icons look crisper across all platforms. 

[format bar icons.zip](https://github.com/wordpress-mobile/WordPress-Editor-Android/files/251787/format.bar.icons.zip)

Please let me know if you need anything else. 

Oh, also — this zip file also contains a new HTML icon, which as Maxime suggests literally spells out HTML, but in Roboto Condensed bold so it should be a bit nicer. I also included a "break link" icon, which it doesn't appear that you'll be using — nonetheless it's there should you need it.

**Comment by aforcier** [comment]
Thanks @jasmussen!

The new icons appear larger than the old ones, is that normal? Here's the format bar with just the bold button changed to a gridicon:

![370-bold-gridicon](https://cloud.githubusercontent.com/assets/9613966/15079217/4ac6f898-1385-11e6-8961-7ea8e251f381.png)

They're the same size, but the new ones have less padding:

<img width="121" alt="370-bold-face-off" src="https://cloud.githubusercontent.com/assets/9613966/15079260/80fc54a8-1385-11e6-8a5a-f540fb8cdde2.png">

(new | old)

**Comment by jasmussen** [comment]
Gotcha, thanks for the comparison! I'll add some more padding to the icons and get you a new set early next week. Do you have these in a branch? Maybe I can dust off my Android Studio and see it in action as I fix?

**Comment by aforcier** [comment]
Thanks! Here's my working branch with all the icons replaced with the ones you gave me: https://github.com/wordpress-mobile/WordPress-Editor-Android/tree/issue/370-dashicons-to-gridicons

**Comment by aforcier** [comment]
I'm looking into changing the icon size from `44dp` to `48dp` - I seem to recall that might have come up in the past. The problem is that in the past we tried to size the format bar so that it wouldn't need to be scrolled on phones of a certain size and up (the cut-off was 360dp, below that you get a scrollbar). Increasing the icon size would push that cut-off higher, and certain phones (I think the Nexus 4 was one of them) will get a scrollbar, which is a worse experience.

Here's the PR where a lot of these changes were laid out: https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/201

I'll do some more research into which phones would actually be affected by this change (and how popular they are now), maybe it's become a more viable option.

**Comment by jasmussen** [comment]
> I'm looking into changing the icon size from 44dp to 48dp - I seem to recall that might have come up in the past. The problem is that in the past we tried to size the format bar so that it wouldn't need to be scrolled on phones of a certain size and up (the cut-off was 360dp, below that you get a scrollbar). Increasing the icon size would push that cut-off higher, and certain phones (I think the Nexus 4 was one of them) will get a scrollbar, which is a worse experience.

I did some more research, and found out the reason why the icon was an odd size, and why my icons were bigger than the dashicons. Turns out that was connected.

Turns out the the format buttons use a 36dp base icon, and then have 4dp padding! But the padding is baked into the icons themselves, instead of being in added as styles. I don't know what's better to do, but I know for sure this means you can ignore my comment about 48dp, because now the icons will be crisp, since the icon itself has a 36dp base that's being scaled (and 36dp is pixel-compatible with the 24dp grid).

I'm going to provide you TWO zips this time. One zip has icons _without_ the 4dp padding, if you'd like to add the padding in XML instead. The other zip will be a drop-in replacement, where the 4dp padding is baked into the image. Stay tuned.

**Comment by jasmussen** [comment]
Alright, here's a new package:

[visual editor icons, adjusted.zip](https://github.com/wordpress-mobile/WordPress-Editor-Android/files/254775/visual.editor.icons.adjusted.zip)

This pack contains two subfolders. One subfolder, `padding not baked in` has 36dp icons. These icons need 4dp padding around it. The math checks out:

`xxhdpi = 3x = ( 36 * 3 ) + (3 * 4) + (3 * 4) = 132`

So xxhdpi icons in that folder are 108px in dimensions. When you add 2x12 to that you get 132, which is the button size.

If it's arduous to add the padding as XML style, I included a folder, `padding baked in` that features icons with the padding baked in. These should be drop-in replacements, and visually correctly sized. 

**Old:**

![format_bar_button_bold_highlighted_old](https://cloud.githubusercontent.com/assets/1204802/15110931/1cf8721e-15e4-11e6-936d-2807375aeb56.png)

**New:**

![format_bar_button_bold_highlighted](https://cloud.githubusercontent.com/assets/1204802/15110935/2523990a-15e4-11e6-9e1f-8e6f4d40ee5e.png)

**Comment by aforcier** [comment]
> Turns out the the format buttons use a 36dp base icon, and then have 4dp padding! But the padding is baked into the icons themselves, instead of being in added as styles. I don't know what's better to do, but I know for sure this means you can ignore my comment about 48dp, because now the icons will be crisp, since the icon itself has a 36dp base that's being scaled (and 36dp is pixel-compatible with the 24dp grid).

Aha, mystery solved! Thanks for the new assets, I'll give them a spin and open up a PR with them when that's ready.
