### ISSUE TITLE
Comments: Edit previously posted comment/reply

### ISSUE THREAD

**Issue by danielwrobert** [wordpress-mobile/WordPress-Editor-Android#387]
I love using the app to comment on (and reply to comments on) posts. I notice that, after posting a comment/reply, via the Notifications tab, there is no way to go back and edit it (AFAIK).

It seems like the only way to do it is to go through Visit Site and edit from there.

This feature doesn't seem to be in the iOS app either. Hopefully I'm not just missing something! :)

**Comment by rachelmcr** [comment]
When you have permissions to manage comments on a site, you can go to the My Sites screen, select your site, and then select Comments (instead of View Site) to manage and edit your comments.

There is also an open issue to add comment moderation to the Reader (https://github.com/wordpress-mobile/WordPress-Android/issues/1678), which would allow more direct moderation of comments you previously posted.

I'm going to close this issue as I think that addresses your main concern, but please let me know if there's more to be done. :)
