### ISSUE TITLE
When saving an uploaded draft, the view doesn't come back to the post list 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#53]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1397

When saving an already uploaded draft, the view doesn't come back to the post list as soon as the save button is pressed but only after the upload ends.

Feels weird:
https://cloudup.com/c1etFKFpqob

**Comment by rachelmcr** [comment]
I retested on a Nexus 9, Android 6.0.1, alpha-5. In this version, the view does not automatically go back to the post list (even after the upload ends). Instead, it shows a spinner over the post preview until the post finishes uploading, and then stays on the preview. You have to manually go back to the post list.

This feels expected to me — since the user decided to view the post preview, it makes sense to return to the post preview after editing/updating (to see the updated preview) and let the user manually go back to the post list when they are done.

I'm closing this issue, since the post-upload flow has also changed since the original issue was opened, but please reopen if this is still a valid issue.
